#!/bin/bash

# Check if script is being run as root
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

# Add localhost resolution to /etc/hosts
echo "127.0.0.2    localhost" >> /etc/hosts

# Add Facebook.com resolution to /etc/hosts
echo "8.8.8.8      facebook.com" >> /etc/hosts

# Flush DNS cache
systemd-resolve --flush-caches

